"""A configuration declaring a hook is not a hook, and the difference is invisible from inside.

Measured 2026-08-12 across two checkouts of two different projects, both declaring pre-push hooks:
ZERO non-sample hook files on disk in either. Every push from either had run none of them -- and the
prose in both repositories said the pushes were guarded. That is a lie about a GUARD'S SCOPE, the
variant that makes a reader route AROUND a check they believe is watching.

WHAT THESE TESTS BUILD: real git repositories under `tmp_path` with real configurations, and hook
files written to whatever directory `git rev-parse --git-path hooks` names for them -- including,
deliberately, one repository whose `core.hooksPath` points somewhere else entirely. Nothing here
runs `pre-commit install`: the hook files are written by hand from pre-commit's own generated
template, so the fixture states exactly what "installed" and "stale" mean rather than inheriting an
untested belief about them from the tool.

WHAT THEY CANNOT SEE: nothing here asserts that an installed hook WORKS. `installed` means a live
file pointing at this configuration, which is a strictly weaker claim than "this hook passes", and
the module says so in those words rather than in the word "installed" alone.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from agent_swarm.hooks import (
    ABSENT,
    FOREIGN,
    INSTALLED,
    NOTHING_DECLARED,
    PROTECTED,
    STALE,
    UNPROTECTED,
    declared_stages,
    hook_installation,
    hooks_dir,
    report_installation,
)

#: pre-commit's own generated shim, reduced to the two lines that carry its identity: the marker it
#: stamps, and the templated ARGS that say WHICH configuration and WHICH stage it was installed for.
_GENERATED = """#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=''
ARGS=(hook-impl --config={config} --hook-type={hook_type})
# end templated
exec pre-commit "${{ARGS[@]}}"
"""

#: A hand-written hook nobody generated -- the case where re-installing DESTROYS work.
_HANDWRITTEN = '#!/bin/sh\nexec make lint\n'

_CONFIG = """repos:
  - repo: https://example.invalid/upstream
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml

  - repo: local
    hooks:
      - id: commit-message
        stages: [commit-msg]
      - id: the-suite
        name: the whole suite
        stages: [pre-push]
      - id: bump-version
        stages: [pre-push]
"""


def _git(repo: Path, *args: str) -> None:
    # timeout: a git call that hangs would park the suite at 0% CPU rather than failing.
    subprocess.run([shutil.which('git') or 'git', *args], cwd=repo, check=True, capture_output=True, timeout=60)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A real repository declaring three stages: pre-commit, commit-msg, pre-push."""
    root = tmp_path / 'repo'
    root.mkdir()
    _git(root, 'init', '-q')
    (root / '.pre-commit-config.yaml').write_text(_CONFIG, encoding='utf-8')
    return root


def _install(repo: Path, hook_type: str, *, config: str = '.pre-commit-config.yaml') -> Path:
    """Write a generated hook into the directory GIT names -- never a hand-built `.git/hooks`."""
    path = hooks_dir(repo) / hook_type
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_GENERATED.format(config=config, hook_type=hook_type), encoding='utf-8')
    return path


# --- what the configuration declares -----------------------------------------------------------


def test_the_declared_set_is_read_from_the_configuration_not_from_the_caller(repo: Path) -> None:
    """Three stages, and the two hooks naming no `stages:` fall to pre-commit's default."""
    assert declared_stages(repo / '.pre-commit-config.yaml') == {
        'commit-msg': ('commit-message',),
        'pre-commit': ('trailing-whitespace', 'check-toml'),
        'pre-push': ('the-suite', 'bump-version'),
    }


def test_a_deprecated_stage_spelling_names_the_same_hook_type(tmp_path: Path) -> None:
    """`stages: [push]` installs the pre-push hook; reading it literally invents a missing hook."""
    config = tmp_path / '.pre-commit-config.yaml'
    config.write_text('repos:\n  - repo: local\n    hooks:\n      - id: x\n        stages: [push]\n', encoding='utf-8')
    assert declared_stages(config) == {'pre-push': ('x',)}


def test_a_file_this_cannot_read_raises_rather_than_declaring_nothing(tmp_path: Path) -> None:
    """An unparsed configuration and an empty one are different findings, so they are not one value."""
    config = tmp_path / '.pre-commit-config.yaml'
    config.write_text('{"repos": [{"repo": "local", "hooks": [{"id": "x"}]}]}\n', encoding='utf-8')
    with pytest.raises(ValueError, match='not a pre-commit configuration'):
        declared_stages(config)

    config.write_text('repos: []\n', encoding='utf-8')
    with pytest.raises(ValueError, match='unread file'):
        declared_stages(config)


# --- where the hooks directory IS --------------------------------------------------------------


def test_the_hooks_directory_is_the_one_core_hookspath_redirects_to(repo: Path) -> None:
    """A guard appending `.git/hooks` answers about a directory git is not consulting."""
    elsewhere = repo.parent / 'shared-hooks'
    elsewhere.mkdir()
    _git(repo, 'config', 'core.hooksPath', elsewhere.as_posix())

    assert hooks_dir(repo).resolve() == elsewhere.resolve()
    assert hooks_dir(repo).resolve() != (repo / '.git' / 'hooks').resolve()

    # And the redirect is followed end to end: installing THERE reads as installed.
    (elsewhere / 'pre-push').write_text(
        _GENERATED.format(config='.pre-commit-config.yaml', hook_type='pre-push'), encoding='utf-8'
    )
    by_stage = {stage.stage: stage for stage in hook_installation(repo).stages}
    assert by_stage['pre-push'].status == INSTALLED


def test_a_worktree_resolves_to_the_main_checkouts_shared_hooks_directory(repo: Path) -> None:
    """A worktree does NOT get its own hooks directory, so a lane's answer is the main tree's."""
    _git(repo, 'config', 'user.email', 't@t')
    _git(repo, 'config', 'user.name', 't')
    _git(repo, 'add', '.pre-commit-config.yaml')
    _git(repo, 'commit', '-qm', 'base')
    lane = repo.parent / 'lane'
    _git(repo, 'worktree', 'add', '-q', '--detach', lane.as_posix())

    assert hooks_dir(lane).resolve() == hooks_dir(repo).resolve()
    assert not (lane / '.git' / 'hooks').exists()


# --- the two failure modes, which are NOT one --------------------------------------------------


def test_declared_but_absent_is_the_current_state_of_a_fresh_checkout(repo: Path) -> None:
    """The defect itself: three stages declared, zero hook files, and it must SAY so."""
    report = hook_installation(repo)

    assert report.verdict == UNPROTECTED
    assert {stage.stage for stage in report.failing} == {'pre-commit', 'commit-msg', 'pre-push'}
    assert {stage.status for stage in report.stages} == {ABSENT}
    assert report.stages[0].path.parent == hooks_dir(repo)


def test_present_but_stale_is_a_different_finding_from_absent(repo: Path) -> None:
    """A hook installed against ANOTHER configuration is present, and protects nothing here."""
    _install(repo, 'pre-push', config='.pre-commit-config-old.yaml')
    _install(repo, 'commit-msg')

    by_stage = {stage.stage: stage for stage in hook_installation(repo).stages}
    assert by_stage['pre-push'].status == STALE
    assert 'pre-commit-config-old.yaml' in by_stage['pre-push'].detail
    assert by_stage['commit-msg'].status == INSTALLED
    assert by_stage['pre-commit'].status == ABSENT
    # The whole point: the three statuses are three values, not one boolean.
    assert len({by_stage['pre-push'].status, by_stage['commit-msg'].status, by_stage['pre-commit'].status}) == 3


def test_a_hook_installed_into_the_wrong_slot_is_stale_not_installed(repo: Path) -> None:
    """`--hook-type=pre-commit` sitting in the `pre-push` file runs the wrong set of hooks."""
    path = hooks_dir(repo) / 'pre-push'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_GENERATED.format(config='.pre-commit-config.yaml', hook_type='pre-commit'), encoding='utf-8')

    by_stage = {stage.stage: stage for stage in hook_installation(repo).stages}
    assert by_stage['pre-push'].status == STALE
    assert 'pre-commit' in by_stage['pre-push'].detail


def test_someone_elses_hook_is_neither_installed_nor_stale(repo: Path) -> None:
    """Re-installing over a hand-written hook DELETES work, so it cannot read as pre-commit's."""
    path = hooks_dir(repo) / 'pre-commit'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_HANDWRITTEN, encoding='utf-8')

    by_stage = {stage.stage: stage for stage in hook_installation(repo).stages}
    assert by_stage['pre-commit'].status == FOREIGN
    assert 'overwrite' in by_stage['pre-commit'].detail


def test_every_stage_installed_reads_as_protected(repo: Path) -> None:
    """The guard must be able to go GREEN, or it is asserting a constant."""
    for hook_type in ('pre-commit', 'commit-msg', 'pre-push'):
        _install(repo, hook_type)

    report = hook_installation(repo)
    assert report.verdict == PROTECTED
    assert report.failing == ()


# --- the third value ---------------------------------------------------------------------------


def test_a_repository_declaring_nothing_is_not_a_repository_installing_nothing(tmp_path: Path) -> None:
    """No configuration is the ABSENCE of the question -- never a pass, and never a failure."""
    bare = tmp_path / 'bare'
    bare.mkdir()
    _git(bare, 'init', '-q')

    report = hook_installation(bare)
    assert report.verdict == NOTHING_DECLARED
    assert report.config is None
    assert report.stages == ()


def test_the_three_answers_are_three_exit_codes(repo: Path, tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    """0 / 1 / 2, so a caller can tell "nothing declared" from "fully installed"."""
    assert report_installation(['--repo', str(repo)]) == 1
    assert 'UNPROTECTED' in capsys.readouterr().out

    for hook_type in ('pre-commit', 'commit-msg', 'pre-push'):
        _install(repo, hook_type)
    assert report_installation(['--repo', str(repo)]) == 0

    bare = tmp_path / 'nothing'
    bare.mkdir()
    _git(bare, 'init', '-q')
    assert report_installation(['--repo', str(bare)]) == 2
    assert 'NOTHING DECLARED' in capsys.readouterr().out
